spring.application.name=21Nov_Flight_Project_Flux

#spring.data.r2dbc.repositories.enabled=true
spring.r2dbc.url=r2dbc:mysql://localhost:3306/21nov_flight_flux
spring.r2dbc.username=root
spring.r2dbc.password=root
